### ISSUE TITLE
Reconciling string.h

### ISSUE THREAD

**Issue by jaspersong** [chasebroder/A1-part2#3]
We are currently trying to reconcile string.h, and we have determined that the following functions should be added to the spec:

```
unsigned long length()
```

Thank you.

**Comment by chasebroder** [comment]
Hi Joe,

That seems reasonable to me. We'd just want to do size_t instead of unsigned long. Let me know if that works!

**Comment by jaspersong** [comment]
Yep that's fair. That would be great. Thanks!

**Comment by chasebroder** [comment]
Changes are in master. Have a good night!

**Comment by chasebroder** [comment]
Be on the lookout for a minor change to the tests to include this function. Thanks!
