### ISSUE TITLE
Class-wide reconciliation of object.h and string.h

### ISSUE THREAD

**Issue by jaspersong** [chasebroder/A1-part2#5]
A [Piazza post](https://piazza.com/class/k51bluky59n2jr?cid=345) has recently been posted where the class have agreed upon a standard for object.h and string.h. A link to the API in question is [here](https://github.com/chasebish/cwc_object_string), in order to ease the work needed for assignment 2.

**Comment by chasebroder** [comment]
Hey,

We're ok with updating our interface to resemble the class standard. Just let us know what method/constructor signatures you'd like us to add!
