### ISSUE TITLE
Handling invalid indexes when removing and getting elements

### ISSUE THREAD

**Issue by jaspersong** [chasebroder/A1-part2#6]
When removing and getting elements at particular indices, what should the behavior be? What sort of error should it be throwing? Should it terminate the program? Should it return a nullptr instead? There should also be some test cases in test-array.cpp in order to test invalid indices as well.

**Comment by chasebroder** [comment]
If trying to get/insert at an out-of-bounds index, the program should print an index out-of-bounds statement and terminate. We tested positive behavior in our cases and aren't really sure how we could test this invalid behavior

**Comment by chasebroder** [comment]
Closing this issue to clean up issues list. Please file a new one if you have further questions
