### ISSUE TITLE
Don't forget to update tests to match design!

### ISSUE THREAD

**Issue by bendavp** [chasebroder/A1-part2#7]
Just a little reminder to update the tests now that we have introduced 4 new `Array`s. Thanks in advance!

**Comment by chasebroder** [comment]
We're currently working on the updated tests and will have those merged into master tomorrow. Sorry for the delay!

I have the tests for the float and int arrays ready on my branch (chase) if you want to give those a look. We'll also be consolidating the tests for the default array into one method and adding the tests for the remaining arrays.

**Comment by bendavp** [comment]
No rush, all good! Just wanted to open an issue so it's not totally forgotten about.

**Comment by chasebroder** [comment]
Tests are set and merged into master. Thanks for your patience! Closing this issue but feel free to reach out with additional questions
