### ISSUE TITLE
Return value of set

### ISSUE THREAD

**Issue by jaspersong** [chasebroder/A1-part2#8]
We noticed that the set function for the arrays have a return value. The function documentation doesn't say what it returns, and the tests don't use the return value of set either. Is the function supposed to have a return value of void? Or is it supposed to return the item that was set into the array, if it was successfully set?

**Comment by chasebroder** [comment]
We'll want this to return to return the old value that we replaced. Sorry for not specifying. I'll update the tests too to reflect this.

**Comment by chasebroder** [comment]
Changes made and pushed to master. I updated documentation for set and checked return value in tests
